// <auto-generated />
using FAbackend.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAbackend.Infra.Data.Migrations
{
	[DbContext(typeof(ApplicationContext))]
	[Migration("20230607052649_AddDomainEntities")]
	partial class AddDomainEntities
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.5")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("FAbackend.Domain.Entities.Affiliated", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

					b.Property<int>("CreatorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("VARCHAR(100)");

					b.HasKey("Id");

					b.HasIndex("CreatorId");

					b.ToTable("Affiliateds", (string)null);
				});

			modelBuilder.Entity("FAbackend.Domain.Entities.Creator", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("VARCHAR(100)");

					b.HasKey("Id");

					b.ToTable("Creators", (string)null);
				});

			modelBuilder.Entity("FAbackend.Domain.Entities.Affiliated", b =>
				{
					b.HasOne("FAbackend.Domain.Entities.Creator", "Creator")
						.WithMany("Affiliateds")
						.HasForeignKey("CreatorId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Creator");
				});

			modelBuilder.Entity("FAbackend.Domain.Entities.Creator", b =>
				{
					b.Navigation("Affiliateds");
				});
#pragma warning restore 612, 618
		}
	}
}
